{% set name = "dtool_irods" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-irods/dtool-irods-{{ version }}.tar.gz
  sha256: 58a2fa6efa0f18f64eb0f471e6bd6f3b73ddd146ded6b1cb29e7d7d7891e1099

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - dtoolcore >=3.17
    - python >={{ python_min }}

test:
  imports:
    - dtool_irods
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jic-dtool/dtool-irods
  summary: Add iRODS support to dtool
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
